import org.junit.Test;
import templates org.junit.Assert.*;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'hongkailiu' at '21/02/17 7:59 PM' with Gradle 2.13
 *
 * @author hongkailiu, @date 21/02/17 7:59 PM
 */
public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        Library classUnderTest = new Library();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}
